import jsPDF from "jspdf";


export const generateReport = (
  disease: string,
  result: any
) => {


  const pdf = new jsPDF();



  // Title

  pdf.setFontSize(22);

  pdf.setTextColor(0, 150, 200);

  pdf.text(
    "PredictWell AI Health Report",
    20,
    25
  );



  // Divider

  pdf.setDrawColor(200,200,200);

  pdf.line(
    20,
    32,
    190,
    32
  );



  pdf.setTextColor(0,0,0);



  pdf.setFontSize(15);



  pdf.text(
    `Disease: ${disease}`,
    20,
    55
  );



  pdf.text(
    `Risk Level: ${result.risk}`,
    20,
    70
  );



  pdf.text(
    `Prediction Probability: ${result.probability}%`,
    20,
    85
  );




  pdf.setFontSize(16);


  pdf.text(
    "Health Recommendations",
    20,
    115
  );



  pdf.setFontSize(13);



  let y = 135;



  if(
    result.recommendations &&
    result.recommendations.length > 0
  ){


    result.recommendations.forEach(
      (item:string)=>{


        pdf.text(
          `• ${item}`,
          25,
          y
        );


        y += 12;


      }
    );


  }
  else{


    pdf.text(
      "No recommendations available",
      25,
      y
    );


  }





  // Footer

  pdf.setFontSize(10);

  pdf.setTextColor(100,100,100);


  pdf.text(
    "Generated by PredictWell AI Healthcare Platform",
    20,
    280
  );




  pdf.save(
    `${disease}_PredictWell_Report.pdf`
  );

};